apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  params: 
  - name: message
    description: "Message Body"
  tasks:
    - name: sample-task
      taskRef:
        name: sample-task
      params:
        - name: message
          value: $(params.message)
